name: Deploy the website
on:
  push:
    branches:
      - main
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create build directory
        run: mkdir -p build

      - name: Copy index.html to build directory
        if: success()
        run: cp index.html build/

      - name: Set up SSH key
        if: success()
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        
      - name: Create temporary directories on the server
        if: success()
        run: |
          ssh -i ~/.ssh/deploy_key "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" "mkdir -p /tmp/httpdocs.bak"
          ssh -i ~/.ssh/deploy_key "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" "mkdir -p /tmp/httpdocs.new"

      - name: Copy the build directory to the server using scp
        if: success()
        run: scp -i ~/.ssh/deploy_key -r build/* "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/tmp/httpdocs.new/"

      - name: Back up the current website
        if: success()
        run: |
          ssh -i ~/.ssh/deploy_key "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" "mv /mariogemoll.com/httpdocs/* /tmp/httpdocs.bak/"

      - name: Move new files to the live directory
        if: success()
        run: |
          ssh -i ~/.ssh/deploy_key "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" "mv /tmp/httpdocs.new/* /mariogemoll.com/httpdocs/"

      - name: Remove the temporary directories
        if: success()
        run: |
          ssh -i ~/.ssh/deploy_key "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" "rm -rf /tmp/httpdocs.bak"
          ssh -i ~/.ssh/deploy_key "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" "rm -rf /tmp/httpdocs.new"
